# Generated by Django 3.1.7 on 2021-04-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi_name', models.CharField(max_length=32)),
                ('desi_date', models.DateField(auto_now=True)),
                ('eng_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_eng', to='mag.engin')),
            ],
        ),
    ]
